# Various utilities
SYSTEM_UTILS=(
  artix-games-launcher
  brave-bin
  cataclysm-dda
  cockatrice
  dolphin
  floorp
  lutris
  neofetch
  openvpn
  orca-slicer
  polymc
  rpcs3
  starship
  steam
  stow
  waybar
  wofi
  xwaylandvideobridge
)

# Development tools
DEV_TOOLS=(
  git
  neovim
  python
  vim
  wezterm
)

DESKTOP=(
  plasma-meta
)

MEDIA=(
  vlc
  gimp
  spectacle
  obs-studio
  kdenlive
)

FONTS=(
  ttf-jetbrains-mono
  ttf-jetbrains-mono-nerd
)

SERVICES=(
  NetworkManager.service
)
