# Various utilities
SYSTEM_UTILS=(
	discord
	dolphin
	fastfetch
	floorp
	iwd
	openvpn
  	orca-slicer
	rofi
	spotify-launcher
	starship
	stow
	xwaylandvideobridge
)

# Development tools
DEV_TOOLS=(
	code
	git
	neovim
	kitty
)

# Preffered Desktop Environments
KDE=(
	plasma-meta
	plasma6-applets-plasmusic-toolbar
)

HYPRLAND=(
	hyprland
	hyprpaper
	hyprshot
	waybar
)

GAMES=(
	artix-games-launcher
	cataclysm-dda
	cockatrice
	lutris
	polymc
	rpcs3
	steam
)

MEDIA=(
	gimp
	kdenlive
	obs-studio
	spectacle
	vlc
)

FONTS=(
	ttf-jetbrains-mono
	ttf-jetbrains-mono-nerd
)

SERVICES=(
	NetworkManager.service
)

LAPTOP_UTILS={
	discord
	dolphin
	fastfetch
	iwd
	openvpn
	starship
	stow
	waybar
	rofi
}

LAPTOP_GAMES={
	polymc
	steam
}

LAPTOP_DEV={
	code
	git
	neovim
	kitty
}

LAPTOP_MEDIA={
	gimp
	spectacle
	vlc
}

LAPTOP_FONTS={
	ttf-jetbrains-mono
	ttf-jetbrains-mono-nerd
}

LAPTOP_SERVICES={
	NetworkManager.service
}

STOW={
	fastfetch
	fish
	kitty
	starship
	waybar
}
